### ISSUE TITLE
Design database schema for list species service.

### ISSUE THREAD

**Issue by abusalehmdtayeen** [phylotastic/Phylotastic_WebService_Projects#1]

**Comment by hdliv** [comment]
@abusalehmdtayeen  and @hdliv are working the schema

**Comment by arlin** [comment]
Good.   We want to make discrete issues, address them, and then close them.  So, the issue for this ticket -- an initial design-- has been resolved.  The next step is to revise the schema and implement it.  See phylotastic/Phylotastic_WebService_Projects#4
