### ISSUE TITLE
Write code for different modules of species list server

### ISSUE THREAD

**Issue by abusalehmdtayeen** [phylotastic/Phylotastic_WebService_Projects#3]

**Comment by abusalehmdtayeen** [comment]
Started writing code for inserting and querying species list server database.

**Comment by abusalehmdtayeen** [comment]
Finished coding insert and query module for species list server.

**Comment by arlin** [comment]
@abusalehmdtayeen, could you tell us where this code is located?  I looked in the webservice projects repo and I could not find it.

**Comment by abusalehmdtayeen** [comment]
@arlin, all code modules related to species list service are located in https://github.com/phylotastic/Phylotastic_WebService_Projects/tree/master/Phylotastic_SLS_WebServices

I will soon add more features to the species list services.
