### ISSUE TITLE
Revise database schema

### ISSUE THREAD

**Issue by arlin** [phylotastic/Phylotastic_WebService_Projects#4]
Consult with Dail to revise database schema to capture stakeholder needs (80 % rule) as reflected in use-cases.  Implement the schema for storage of lists.

**Comment by hdliv** [comment]
the updated schema has been sent to Abu and he is going over them

**Comment by arlin** [comment]
I see that Abu already made a ticket for creating the database.  So, this is separated into pieces
#4: revise the initial schema (Dail and Abu working together)
#2: implement the schema (Abu)
#5: format initial lists so that Abu can import them into schema (Dail)

**Comment by abusalehmdtayeen** [comment]
The file https://github.com/phylotastic/Phylotastic_WebService_Documentation/blob/master/SpeciesListServer/SpeciesListArchiveGuide.md describes what type of files user can upload, what are the file formats, data types etc. It needs to be updated according to the new schema. Dail will have a look at it and send feedback.

**Comment by arlin** [comment]
Good!  It looks like you have designed this carefully to meet the Darwin Core Archive spec.

**Comment by abusalehmdtayeen** [comment]
Completed reviewing database schema. Based on the schema and requirements I did some research to chose database system to use for species list server

**Comment by arlin** [comment]
@abusalehmdtayeen, I think you have revised the db schema.  If so, please move this ticket into "in review".
